#!/usr/bin/env bash
# Generate a pi extension from applied hooks.
# Reads applied hooks from state file (which includes catalog paths).
#
# Usage: generate-extension.sh <state_file>
# Output: TypeScript extension source on stdout

set -euo pipefail

STATE_FILE="$1"

if [ ! -f "$STATE_FILE" ]; then
  echo "Error: State file not found: $STATE_FILE" >&2
  exit 1
fi

# Read applied hooks — each entry has name and catalog path
HOOK_COUNT=$(jq '.applied | length' "$STATE_FILE" 2>/dev/null)
if [ "$HOOK_COUNT" -eq 0 ]; then
  echo "Error: No hooks applied" >&2
  exit 1
fi

# Resolve catalog files from state
HOOKS=()
for i in $(seq 0 $((HOOK_COUNT - 1))); do
  name=$(jq -r ".applied[$i].name" "$STATE_FILE")
  catalog=$(jq -r ".applied[$i].catalog" "$STATE_FILE")
  file="$catalog/${name}.json"
  if [ ! -f "$file" ]; then
    echo "Error: Hook '$name' not found at $file (catalog may have moved or been uninstalled)" >&2
    exit 1
  fi
  HOOKS+=("$file")
done

# Map generic event names to pi event names
map_event() {
  case "$1" in
    session-start)   echo "session_start" ;;
    session-end)     echo "session_shutdown" ;;
    before-prompt)   echo "before_agent_start" ;;
    before-compact)  echo "session_before_compact" ;;
    before-tool)     echo "tool_call" ;;
    after-tool)      echo "tool_result" ;;
    agent-stop)      echo "agent_end" ;;
    *) echo "Error: Unknown event '$1'" >&2; return 1 ;;
  esac
}

# Generate TypeScript
cat <<'HEADER'
// Generated by hookers apply — do not edit manually.
// Regenerate with: hookers apply
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

export default function (pi: ExtensionAPI) {
HEADER

for file in "${HOOKS[@]}"; do
  name=$(jq -r '.name' "$file")
  desc=$(jq -r '.description' "$file")
  on=$(jq -r '.on' "$file")
  action=$(jq -r '.action' "$file")
  command=$(jq -r '.command // ""' "$file")
  matcher=$(jq -r '.matcher // ""' "$file")

  pi_event=$(map_event "$on") || exit 1

  echo ""
  echo "  // $name — $desc"

  case "$action" in
    run)
      cat <<EOF
  pi.on("$pi_event", async () => {
    await pi.exec("bash", ["-c", $(jq -n --arg c "$command" '$c')]);
  });
EOF
      ;;

    inject)
      if [ "$pi_event" = "before_agent_start" ]; then
        cat <<EOF
  pi.on("$pi_event", async () => {
    const result = await pi.exec("bash", ["-c", $(jq -n --arg c "$command" '$c')]);
    if (result.code === 0 && result.stdout.trim()) {
      return {
        message: {
          customType: "hookers:$name",
          content: result.stdout.trim(),
          display: false,
        },
      };
    }
  });
EOF
      else
        echo "Error: inject action only supported on before-prompt event (got '$on' for hook '$name')" >&2
        exit 1
      fi
      ;;

    block)
      if [ "$pi_event" = "session_before_compact" ]; then
        cat <<EOF
  pi.on("$pi_event", async () => {
    return { cancel: true };
  });
EOF
      elif [ "$pi_event" = "tool_call" ]; then
        if [ -n "$matcher" ] && [ -n "$command" ]; then
          cat <<EOF
  pi.on("$pi_event", async (event) => {
    if (new RegExp($(jq -n --arg m "$matcher" '$m')).test(event.toolName)) {
      const result = await pi.exec("bash", ["-c", $(jq -n --arg c "$command" '$c')]);
      if (result.code !== 0) {
        return { block: true, reason: result.stderr.trim() || "Blocked by $name hook" };
      }
    }
  });
EOF
        elif [ -n "$command" ]; then
          cat <<EOF
  pi.on("$pi_event", async () => {
    const result = await pi.exec("bash", ["-c", $(jq -n --arg c "$command" '$c')]);
    if (result.code !== 0) {
      return { block: true, reason: result.stderr.trim() || "Blocked by $name hook" };
    }
  });
EOF
        else
          cat <<EOF
  pi.on("$pi_event", async () => {
    return { block: true, reason: "Blocked by $name hook" };
  });
EOF
        fi
      else
        cat <<EOF
  pi.on("$pi_event", async () => {
    return { cancel: true };
  });
EOF
      fi
      ;;

    *)
      echo "  // WARNING: Unknown action '$action' for hook '$name'" >&2
      ;;
  esac
done

cat <<'FOOTER'
}
FOOTER
