#!/usr/bin/env bash
# Generate a pi extension from applied hooks.
# Reads applied hooks from state file and catalog, writes hookers.ts.
#
# Usage: generate-extension.sh <state_file> <catalog_dirs...>
# Output: TypeScript extension source on stdout

set -euo pipefail

STATE_FILE="$1"
shift
CATALOG_DIRS=("$@")

if [ ! -f "$STATE_FILE" ]; then
  echo "Error: State file not found: $STATE_FILE" >&2
  exit 1
fi

# Read applied hook names
APPLIED=$(jq -r '.applied[]' "$STATE_FILE" 2>/dev/null)
if [ -z "$APPLIED" ]; then
  echo "Error: No hooks applied" >&2
  exit 1
fi

# Collect catalog entries for applied hooks
HOOKS=()
for name in $APPLIED; do
  found=""
  for dir in "${CATALOG_DIRS[@]}"; do
    file="$dir/${name}.json"
    if [ -f "$file" ]; then
      found="$file"
      break
    fi
  done
  if [ -z "$found" ]; then
    echo "Warning: Applied hook '$name' not found in catalog, skipping" >&2
    continue
  fi
  HOOKS+=("$found")
done

if [ ${#HOOKS[@]} -eq 0 ]; then
  echo "Error: No valid hooks found" >&2
  exit 1
fi

# Map generic event names to pi event names
map_event() {
  case "$1" in
    session-start)   echo "session_start" ;;
    session-end)     echo "session_shutdown" ;;
    before-prompt)   echo "before_agent_start" ;;
    before-compact)  echo "session_before_compact" ;;
    before-tool)     echo "tool_call" ;;
    after-tool)      echo "tool_result" ;;
    agent-stop)      echo "agent_end" ;;
    *) echo "Error: Unknown event '$1'" >&2; return 1 ;;
  esac
}

# Generate TypeScript
cat <<'HEADER'
// Generated by hookers apply — do not edit manually.
// Regenerate with: hookers apply
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

export default function (pi: ExtensionAPI) {
HEADER

for file in "${HOOKS[@]}"; do
  name=$(jq -r '.name' "$file")
  desc=$(jq -r '.description' "$file")
  on=$(jq -r '.on' "$file")
  action=$(jq -r '.action' "$file")
  command=$(jq -r '.command // ""' "$file")
  matcher=$(jq -r '.matcher // ""' "$file")

  pi_event=$(map_event "$on") || exit 1

  echo ""
  echo "  // $name — $desc"

  case "$action" in
    run)
      cat <<EOF
  pi.on("$pi_event", async (_event, ctx) => {
    await pi.exec("bash", ["-c", $(jq -n --arg c "$command" '$c')]);
  });
EOF
      ;;

    inject)
      if [ "$pi_event" = "before_agent_start" ]; then
        cat <<EOF
  pi.on("$pi_event", async (_event, ctx) => {
    const result = await pi.exec("bash", ["-c", $(jq -n --arg c "$command" '$c')]);
    if (result.code === 0 && result.stdout.trim()) {
      return {
        message: {
          customType: "hookers:$name",
          content: result.stdout.trim(),
          display: false,
        },
      };
    }
  });
EOF
      else
        echo "  // WARNING: inject action only supported on before-prompt event" >&2
      fi
      ;;

    block)
      if [ "$pi_event" = "session_before_compact" ]; then
        cat <<EOF
  pi.on("$pi_event", async (_event, ctx) => {
    return { cancel: true };
  });
EOF
      elif [ "$pi_event" = "tool_call" ]; then
        if [ -n "$matcher" ]; then
          cat <<EOF
  pi.on("$pi_event", async (event, ctx) => {
    if (new RegExp($(jq -n --arg m "$matcher" '$m')).test(event.toolName)) {
      if ($(jq -n --arg c "$command" '$c')) {
        const result = await pi.exec("bash", ["-c", $(jq -n --arg c "$command" '$c')]);
        if (result.code !== 0) {
          return { block: true, reason: result.stderr.trim() || "Blocked by $name hook" };
        }
      }
    }
  });
EOF
        else
          cat <<EOF
  pi.on("$pi_event", async (event, ctx) => {
    const result = await pi.exec("bash", ["-c", $(jq -n --arg c "$command" '$c')]);
    if (result.code !== 0) {
      return { block: true, reason: result.stderr.trim() || "Blocked by $name hook" };
    }
  });
EOF
        fi
      else
        cat <<EOF
  pi.on("$pi_event", async (_event, ctx) => {
    return { cancel: true };
  });
EOF
      fi
      ;;

    *)
      echo "  // WARNING: Unknown action '$action' for hook '$name'" >&2
      ;;
  esac
done

cat <<'FOOTER'
}
FOOTER
